name: Emulate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Set up the QEMU static binaries
          uses: docker/setup-qemu-action@v1
          with:
              platforms: all

        - run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset --name arm_container

        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: 'uname -a'

        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: >
                  bash -c
                  "apt-get update &&
                  apt-get install -y python3.6 &&
                  python3.6 --version &&
                  pwd ttt &&
                  touch ttt &&
                  ls &&
                  cp arm_container:/github/workspace/ttt . &&
                  python3.6 -c\"import platform; print(platform.machine())\""

        - uses: actions/upload-artifact@v3
          with:
              name: ttt
              path: .


