name: Emulate

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        #python-version: ['2.7', '3.7', '3.8']

    steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Set up the QEMU static binaries
          uses: docker/setup-qemu-action@v1
          with:
              platforms: all

        - run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset

        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: 'uname -a'

        - run: |
            docker container ls

        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: >
                  bash -c
                  "apt-get update &&
                  apt-get install -y python3.6 &&
                  python3.6 --version &&
                  touch ttt &&
                  echo ${{ matrix.os }}
                  ls &&
                  python3.6 -c\"import platform; print(platform.machine())\""

        - run: |
            ls

        - uses: actions/upload-artifact@v3
          with:
              name: ttt
              path: ./ttt


