name: Rust on Arm

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repository
          uses: actions/checkout@v2
        - name: Set up the QEMU static binaries
          uses: docker/setup-qemu-action@v1
          with:
              platforms: all

        - run: |
            docker run --rm --privileged multiarch/qemu-user-static:register --reset

            #need to hardcode ubuntu/windows/macOs here I think
        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: 'uname -a'

        - run: |
            docker container ls

        - uses: docker://multiarch/ubuntu-core:arm64-bionic
          with:
              args: >
                  bash -c 
                  "apt-get update &&
                  apt-get install -y curl &&
                  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
                  source $HOME/.cargo/env &&
                  cargo --help &&
                  cargo update -p libc &&
                  cargo install tree-sitter-cli "

        - run: |
            ls

        - uses: actions/upload-artifact@v3
          with:
              name: wheel
              path: ./dist/*.whl


